### ISSUE TITLE
option tcplog is not working

### ISSUE THREAD

**Issue by flik** [HariSekhon/HAProxy-configs#1]
I have used your config and everything works perfectly just this [option tcplog] is giving this warninng.

`[WARNING] 030/112145 (1) : parsing [/usr/local/etc/haproxy/haproxy.cfg:31] : backend 'mysql' : 'option tcplog' directive is ignored in backends.`

**Comment by HariSekhon** [comment]
Thanks for raising this. It appears HAProxy used to support this directive, but removed it for backends in HAProxy 1.8.

What version of haproxy are you using, I assume 1.8 or 1.9?

Compare the section in the two versions of the manual:

https://cbonte.github.io/haproxy-dconv/1.7/configuration.html#4-option%20tcplog

http://cbonte.github.io/haproxy-dconv/1.8/configuration.html#4-option%20tcplog

I have removed all option tcplog statements from all configurations.
