### ISSUE TITLE
Why do you not use Knox?

### ISSUE THREAD

**Issue by disoardi** [HariSekhon/HAProxy-configs#2]
Why do you don't use haproxy for balance the connections to knox nodes and use knox for authentication and proxy to the services?

**Comment by HariSekhon** [comment]
Thanks for raising this, it is on the todo list to update the Hortonworks HAProxy configs, I'll include adding Knox HAProxy.

Sometimes it's easier and faster to just use HAProxy than Knox, where you may want to run a script against a given Hadoop ecosystem master for administration and always have it work.

**Comment by 0iras0r** [comment]
Hi Hari! Thanks for all your efforts with these amazing tools.
About this... I'm doing some test, but I'm not skilled regarding haproxy.
The Apache Knox documentation use httpd as load balancer (it works very well, I checked), hope this helps... https://knox.apache.org/books/knox-1-2-0/user-guide.html#High+Availability
It could be really great to translate the httpd configuration to an haproxy one =)

Regards,
Rosario

**Comment by HariSekhon** [comment]
Hortonworks is dead and I don't know if anyone still uses Knox, I certainly don't work on that tech any more, so closing this unless anybody wants to contribute a config for that one.
